name: Run Streamlit App (example)

on:
  push:
    branches: [ main ]

jobs:
  run-app:
    runs-on: ubuntu-latest

    env:
      CHAT_API: ${{ secrets.CHAT_API }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run app logic
      run: |
        python your_script.py
